<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BeatSeeder extends Seeder
{

    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        // Obtener IDs reales por email (robusto)
        $ids = DB::table('usuario')
            ->whereIn('direccion_correo', [
                'carlos@levelbeats.com',
                'miguel@levelbeats.com',
                'nova@levelbeats.com',
            ])
            ->pluck('id', 'direccion_correo');

        $carlos = $ids['carlos@levelbeats.com'] ?? null;
        $miguel = $ids['miguel@levelbeats.com'] ?? null;
        $nova   = $ids['nova@levelbeats.com'] ?? null;

        // Seguridad: si falta alguno, paramos para no romper FK
        if (!$carlos || !$miguel || !$nova) {
            throw new \Exception("Faltan usuarios seed: carlos/miguel/nova. Ejecuta UsuarioSeeder antes.");
        }

        DB::table('beat')->insert([
            [
                'id_usuario' => $carlos,
                'titulo_beat' => 'Lil Tjay x Melodic Trap Type Beat - I Told You (Prod. Ilgu)',
                'genero_musical' => 'Melodic Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => null,
                'precio_base_licencia' => 9.99,
                'url_audio_previsualizacion' => 'media/audio/beats/lil_tjay_x_melodic_trap_type_beat_i_told_you_prod_ilgu.mp3',
                'url_archivo_final' => 'media/audio/beats/lil_tjay_x_melodic_trap_type_beat_i_told_you_prod_ilgu.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(19),
            ],
            [
                'id_usuario' => $miguel,
                'titulo_beat' => 'Lil Tjay x PnB Rock Type Beat - Breath Away Melodic Trap Type Beat - Instrumental',
                'genero_musical' => 'Melodic Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => null,
                'precio_base_licencia' => 9.99,
                'url_audio_previsualizacion' => 'media/audio/beats/lil_tjay_x_pnb_rock_type_beat_breath_away_melodic_trap_type_beat_instrumental.mp3',
                'url_archivo_final' => 'media/audio/beats/lil_tjay_x_pnb_rock_type_beat_breath_away_melodic_trap_type_beat_instrumental.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(18),
            ],
            [
                'id_usuario' => $nova,
                'titulo_beat' => 'Lil Tjay x PnB Rock Type Beat - I\'ll Be There ft. Polo G',
                'genero_musical' => 'Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => null,
                'precio_base_licencia' => 19.99,
                'url_audio_previsualizacion' => 'media/audio/beats/lil_tjay_x_pnb_rock_type_beat_i_ll_be_there_ft_polo_g.mp3',
                'url_archivo_final' => 'media/audio/beats/lil_tjay_x_pnb_rock_type_beat_i_ll_be_there_ft_polo_g.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(17),
            ],
            [
                'id_usuario' => $nova,
                'titulo_beat' => 'Mc Igu x Derek Type Beat - Pipe Prod. Johnny Lowd',
                'genero_musical' => 'Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => null,
                'precio_base_licencia' => 14.99,
                'url_audio_previsualizacion' => 'media/audio/beats/mc_igu_x_derek_type_beat_pipe_prod_johnny_lowd.mp3',
                'url_archivo_final' => 'media/audio/beats/mc_igu_x_derek_type_beat_pipe_prod_johnny_lowd.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(16),
            ],
            [
                'id_usuario' => $nova,
                'titulo_beat' => 'Nav x The Weeknd Type Beat - i don\'t sleep at night',
                'genero_musical' => 'Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => null,
                'precio_base_licencia' => 14.99,
                'url_audio_previsualizacion' => 'media/audio/beats/nav_x_the_weeknd_type_beat_i_don_t_sleep_at_night.mp3',
                'url_archivo_final' => 'media/audio/beats/nav_x_the_weeknd_type_beat_i_don_t_sleep_at_night.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(15),
            ],
            [
                'id_usuario' => $miguel,
                'titulo_beat' => 'OFB SJ x BandoKay x Double L\'z Type Beat Half It (Prod. Yoni)',
                'genero_musical' => 'UK Drill',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => null,
                'precio_base_licencia' => 14.99,
                'url_audio_previsualizacion' => 'media/audio/beats/ofb_sj_x_bandokay_x_double_l_z_type_beat_half_it_prod_yoni.mp3',
                'url_archivo_final' => 'media/audio/beats/ofb_sj_x_bandokay_x_double_l_z_type_beat_half_it_prod_yoni.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(14),
            ],
            [
                'id_usuario' => $miguel,
                'titulo_beat' => 'PnB Rock x Lil Tjay Type Beat - Pastime Melodic Trap Type Beat - Instrumental',
                'genero_musical' => 'Melodic Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => null,
                'precio_base_licencia' => 9.99,
                'url_audio_previsualizacion' => 'media/audio/beats/pnb_rock_x_lil_tjay_type_beat_pastime_melodic_trap_type_beat_instrumental.mp3',
                'url_archivo_final' => 'media/audio/beats/pnb_rock_x_lil_tjay_type_beat_pastime_melodic_trap_type_beat_instrumental.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(13),
            ],
            [
                'id_usuario' => $miguel,
                'titulo_beat' => 'PnB Rock x Lil Tjay Type Beat - Voices Melodic Trap Type Beat - Instrumental',
                'genero_musical' => 'Melodic Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => null,
                'precio_base_licencia' => 29.99,
                'url_audio_previsualizacion' => 'media/audio/beats/pnb_rock_x_lil_tjay_type_beat_voices_melodic_trap_type_beat_instrumental.mp3',
                'url_archivo_final' => 'media/audio/beats/pnb_rock_x_lil_tjay_type_beat_voices_melodic_trap_type_beat_instrumental.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(12),
            ],
            [
                'id_usuario' => $miguel,
                'titulo_beat' => 'Polo g x Lil Baby Type Beat - PATEK Melodic Trap Beat Instrumental',
                'genero_musical' => 'Melodic Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => null,
                'precio_base_licencia' => 9.99,
                'url_audio_previsualizacion' => 'media/audio/beats/polo_g_x_lil_baby_type_beat_patek_melodic_trap_beat_instrumental.mp3',
                'url_archivo_final' => 'media/audio/beats/polo_g_x_lil_baby_type_beat_patek_melodic_trap_beat_instrumental.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(11),
            ],
            [
                'id_usuario' => $carlos,
                'titulo_beat' => 'Polo G x Lil Tjay Type Beat - Millions (prod Ramsey Beatz)',
                'genero_musical' => 'Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => null,
                'precio_base_licencia' => 9.99,
                'url_audio_previsualizacion' => 'media/audio/beats/polo_g_x_lil_tjay_type_beat_millions_prod_ramsey_beatz.mp3',
                'url_archivo_final' => 'media/audio/beats/polo_g_x_lil_tjay_type_beat_millions_prod_ramsey_beatz.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(10),
            ],
            [
                'id_usuario' => $carlos,
                'titulo_beat' => 'Roddy Ricch x Mustard Type Beat "Fly Away"',
                'genero_musical' => 'Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Uplifting',
                'precio_base_licencia' => 29.99,
                'url_audio_previsualizacion' => 'media/audio/beats/roddy_ricch_x_mustard_type_beat_fly_away.mp3',
                'url_archivo_final' => 'media/audio/beats/roddy_ricch_x_mustard_type_beat_fly_away.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(9),
            ],
            [
                'id_usuario' => $carlos,
                'titulo_beat' => 'Sad Piano Juice Wrld Type Beat \'Affection\'',
                'genero_musical' => 'Piano Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Sad',
                'precio_base_licencia' => 24.99,
                'url_audio_previsualizacion' => 'media/audio/beats/sad_piano_juice_wrld_type_beat_affection.mp3',
                'url_archivo_final' => 'media/audio/beats/sad_piano_juice_wrld_type_beat_affection.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(8),
            ],
            [
                'id_usuario' => $carlos,
                'titulo_beat' => 'Sad XXXTentacion x Killstation Type Beat \'Plague\'',
                'genero_musical' => 'Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Sad',
                'precio_base_licencia' => 9.99,
                'url_audio_previsualizacion' => 'media/audio/beats/sad_xxxtentacion_x_killstation_type_beat_plague.mp3',
                'url_archivo_final' => 'media/audio/beats/sad_xxxtentacion_x_killstation_type_beat_plague.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(7),
            ],
            [
                'id_usuario' => $carlos,
                'titulo_beat' => 'Sad XXXTentacion x NF Piano Type Beat Relapse',
                'genero_musical' => 'Piano Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Sad',
                'precio_base_licencia' => 9.99,
                'url_audio_previsualizacion' => 'media/audio/beats/sad_xxxtentacion_x_nf_piano_type_beat_relapse.mp3',
                'url_archivo_final' => 'media/audio/beats/sad_xxxtentacion_x_nf_piano_type_beat_relapse.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(6),
            ],
            [
                'id_usuario' => $carlos,
                'titulo_beat' => 'Speed Melodic Type Beat Trap Instrumental 2020',
                'genero_musical' => 'Melodic Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Energetic',
                'precio_base_licencia' => 14.99,
                'url_audio_previsualizacion' => 'media/audio/beats/speed_melodic_type_beat_trap_instrumental_2020.mp3',
                'url_archivo_final' => 'media/audio/beats/speed_melodic_type_beat_trap_instrumental_2020.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(5),
            ],
            [
                'id_usuario' => $miguel,
                'titulo_beat' => 'Travis Scott Type Beat 2019 - Callejero Base de Trap Instrumental de Trap',
                'genero_musical' => 'Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Street',
                'precio_base_licencia' => 14.99,
                'url_audio_previsualizacion' => 'media/audio/beats/travis_scott_type_beat_2019_callejero_base_de_trap_instrumental_de_trap.mp3',
                'url_archivo_final' => 'media/audio/beats/travis_scott_type_beat_2019_callejero_base_de_trap_instrumental_de_trap.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(4),
            ],
            [
                'id_usuario' => $nova,
                'titulo_beat' => 'TRAVIS SCOTTFRVRFRIDAY TYPE BEAT FANTASIA',
                'genero_musical' => 'Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Epic',
                'precio_base_licencia' => 9.99,
                'url_audio_previsualizacion' => 'media/audio/beats/travis_scottfrvrfriday_type_beat_fantasia.mp3',
                'url_archivo_final' => 'media/audio/beats/travis_scottfrvrfriday_type_beat_fantasia.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(3),
            ],
            [
                'id_usuario' => $nova,
                'titulo_beat' => 'Young Thug x Melodic Trap Type Beat - Gotti (Prod. Ilgu)',
                'genero_musical' => 'Melodic Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => null,
                'precio_base_licencia' => 29.99,
                'url_audio_previsualizacion' => 'media/audio/beats/young_thug_x_melodic_trap_type_beat_gotti_prod_ilgu.mp3',
                'url_archivo_final' => 'media/audio/beats/young_thug_x_melodic_trap_type_beat_gotti_prod_ilgu.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(2),
            ],
            [
                'id_usuario' => $miguel,
                'titulo_beat' => 'Young Thug x Tory Lanez Type Beat - Otherside Trap Instrumental 2019',
                'genero_musical' => 'Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Dark',
                'precio_base_licencia' => 29.99,
                'url_audio_previsualizacion' => 'media/audio/beats/young_thug_x_tory_lanez_type_beat_otherside_trap_instrumental_2019.mp3',
                'url_archivo_final' => 'media/audio/beats/young_thug_x_tory_lanez_type_beat_otherside_trap_instrumental_2019.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subDays(1),
            ],
            [
                'id_usuario' => $miguel,
                'titulo_beat' => 'Элджей x Nebezao Deep House Club Trap Beat - Медуза Feduk Type Beat',
                'genero_musical' => 'Deep House / Club Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Club',
                'precio_base_licencia' => 9.99,
                'url_audio_previsualizacion' => 'media/audio/beats/eldzhei_x_nebezao_deep_house_club_trap_beat_meduza_feduk_type_beat.mp3',
                'url_archivo_final' => 'media/audio/beats/eldzhei_x_nebezao_deep_house_club_trap_beat_meduza_feduk_type_beat.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $carlos,
                'titulo_beat' => 'GUITAR Poorstacy x Iann Dior Type Beat - Isolated (prod. perish)',
                'genero_musical' => 'Pop / Guitar Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Moody',
                'precio_base_licencia' => 19.99,
                'url_audio_previsualizacion' => 'media/audio/beats/guitar_poorstacy_x_iann_dior_type_beat_isolated_prod_perish.mp3',
                'url_archivo_final' => 'media/audio/beats/guitar_poorstacy_x_iann_dior_type_beat_isolated_prod_perish.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subHours(10),
            ],
            [
                'id_usuario' => $carlos,
                'titulo_beat' => 'Iann Dior x Juice WRLD Pop Guitar Type Beat - Have Fun (prod. malloy x Aidan H)',
                'genero_musical' => 'Pop / Guitar Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Uplifting',
                'precio_base_licencia' => 19.99,
                'url_audio_previsualizacion' => 'media/audio/beats/iann_dior_x_juice_wrld_pop_guitar_type_beat_have_fun_prod_malloy_x_aidan_h.mp3',
                'url_archivo_final' => 'media/audio/beats/iann_dior_x_juice_wrld_pop_guitar_type_beat_have_fun_prod_malloy_x_aidan_h.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subHours(9),
            ],
            [
                'id_usuario' => $miguel,
                'titulo_beat' => 'Kidd Keo Type Beat - Codeine (Prod. thatsauce)',
                'genero_musical' => 'Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Dark',
                'precio_base_licencia' => 14.99,
                'url_audio_previsualizacion' => 'media/audio/beats/kidd_keo_type_beat_codeine_prod_thatsauce.mp3',
                'url_archivo_final' => 'media/audio/beats/kidd_keo_type_beat_codeine_prod_thatsauce.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subHours(8),
            ],
            [
                'id_usuario' => $nova,
                'titulo_beat' => 'kwengface x DigDat x C1 UK Drill Type Beat - WRAPPED (PROD BY 3LACKONDABEAT)',
                'genero_musical' => 'UK Drill',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Aggressive',
                'precio_base_licencia' => 14.99,
                'url_audio_previsualizacion' => 'media/audio/beats/kwengface_x_digdat_x_c1_uk_drill_type_beat_wrapped_prod_by_3lackondabeat.mp3',
                'url_archivo_final' => 'media/audio/beats/kwengface_x_digdat_x_c1_uk_drill_type_beat_wrapped_prod_by_3lackondabeat.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subHours(7),
            ],
            [
                'id_usuario' => $nova,
                'titulo_beat' => 'Lil Baby x Meek Mill x Quay Global Type Beat 2020 - Aretha (prod. GLAZER & noah)',
                'genero_musical' => 'Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Hard',
                'precio_base_licencia' => 29.99,
                'url_audio_previsualizacion' => 'media/audio/beats/lil_baby_x_meek_mill_x_quay_global_type_beat_2020_aretha_prod_glazer_noah.mp3',
                'url_archivo_final' => 'media/audio/beats/lil_baby_x_meek_mill_x_quay_global_type_beat_2020_aretha_prod_glazer_noah.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subHours(6),
            ],
            [
                'id_usuario' => $nova,
                'titulo_beat' => 'Lil Baby x Melodic Trap Type Beat - Smokin (Prod. Ilgu)',
                'genero_musical' => 'Melodic Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Confident',
                'precio_base_licencia' => 29.99,
                'url_audio_previsualizacion' => 'media/audio/beats/lil_baby_x_melodic_trap_type_beat_smokin_prod_ilgu.mp3',
                'url_archivo_final' => 'media/audio/beats/lil_baby_x_melodic_trap_type_beat_smokin_prod_ilgu.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subHours(5),
            ],
            [
                'id_usuario' => $nova,
                'titulo_beat' => 'Lil Mosey x Lil Skies x Lil Tecca Type Beat - Cold Like (Prod. Snooza)',
                'genero_musical' => 'Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Chill',
                'precio_base_licencia' => 9.99,
                'url_audio_previsualizacion' => 'media/audio/beats/lil_mosey_x_lil_skies_x_lil_tecca_type_beat_cold_like_prod_snooza.mp3',
                'url_archivo_final' => 'media/audio/beats/lil_mosey_x_lil_skies_x_lil_tecca_type_beat_cold_like_prod_snooza.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subHours(4),
            ],
            [
                'id_usuario' => $miguel,
                'titulo_beat' => 'RV x GHOSTY UK DRILL TYPE BEAT - UNDERGROUND (PROD MIGZ)',
                'genero_musical' => 'UK Drill',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Dark',
                'precio_base_licencia' => 14.99,
                'url_audio_previsualizacion' => 'media/audio/beats/rv_x_ghosty_uk_drill_type_beat_underground_prod_migz.mp3',
                'url_archivo_final' => 'media/audio/beats/rv_x_ghosty_uk_drill_type_beat_underground_prod_migz.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subHours(3),
            ],
            [
                'id_usuario' => $carlos,
                'titulo_beat' => 'AMARGUE - Deep Space Trap Type Beat - Trapani (Instrumental por KIDDKATZ)',
                'genero_musical' => 'Space Trap',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Atmospheric',
                'precio_base_licencia' => 14.99,
                'url_audio_previsualizacion' => 'media/audio/beats/amargue_deep_space_trap_type_beat_trapani_instrumental_por_kiddkatz.mp3',
                'url_archivo_final' => 'media/audio/beats/amargue_deep_space_trap_type_beat_trapani_instrumental_por_kiddkatz.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subHours(2),
            ],
            [
                'id_usuario' => $carlos,
                'titulo_beat' => 'emo rap x lofi type beat - let me down',
                'genero_musical' => 'Emo Rap / Lofi',
                'tempo_bpm' => null,
                'tono_musical' => null,
                'estado_de_animo' => 'Sad',
                'precio_base_licencia' => 9.99,
                'url_audio_previsualizacion' => 'media/audio/beats/emo_rap_x_lofi_type_beat_let_me_down.mp3',
                'url_archivo_final' => 'media/audio/beats/emo_rap_x_lofi_type_beat_let_me_down.mp3',
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => true,
                'fecha_publicacion' => now()->subHours(1),
            ]
        ]);
    }
}
