<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use RuntimeException;

class BeatSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('coleccion_beat')->truncate();
        DB::table('beat')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $carlosId = DB::table('usuario')
            ->where('direccion_correo', 'carlos@levelbeats.com')
            ->value('id');

        $miguelId = DB::table('usuario')
            ->where('direccion_correo', 'miguel@levelbeats.com')
            ->value('id');

        if (!$carlosId || !$miguelId) {
            throw new RuntimeException('Faltan productores. Ejecuta UsuarioSeeder y UsuarioRolSeeder antes.');
        }

        $beats = [
            [
                'id_usuario' => $carlosId,
                'titulo_beat' => 'Amargue - Deep Space Trap Type Beat',
                'genero_musical' => 'Trap',
                'tempo_bpm' => 140,
                'tono_musical' => 'C#',
                'estado_de_animo' => 'Oscuro',
                'precio_base_licencia' => 19.99,
                'url_audio_previsualizacion' => 'media/audio/beats/amargue_deep_space_trap_type_beat_trapani_instrumental_por_kiddkatz.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $miguelId,
                'titulo_beat' => 'Eldzhei x Nebezao - Deep House Club Trap Beat',
                'genero_musical' => 'Deep House',
                'tempo_bpm' => 122,
                'tono_musical' => 'F',
                'estado_de_animo' => 'Atmosferico',
                'precio_base_licencia' => 18.99,
                'url_audio_previsualizacion' => 'media/audio/beats/eldzhei_x_nebezao_deep_house_club_trap_beat_meduza_feduk_type_beat.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $carlosId,
                'titulo_beat' => 'Emo Rap x LoFi Type Beat - Let Me Down',
                'genero_musical' => 'Lo-Fi',
                'tempo_bpm' => 76,
                'tono_musical' => 'D',
                'estado_de_animo' => 'Melancolico',
                'precio_base_licencia' => 17.99,
                'url_audio_previsualizacion' => 'media/audio/beats/emo_rap_x_lofi_type_beat_let_me_down.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $miguelId,
                'titulo_beat' => 'Guitar Poorstacy x Iann Dior Type Beat - Isolated',
                'genero_musical' => 'Emo Trap',
                'tempo_bpm' => 82,
                'tono_musical' => 'E',
                'estado_de_animo' => 'Triste',
                'precio_base_licencia' => 18.99,
                'url_audio_previsualizacion' => 'media/audio/beats/guitar_poorstacy_x_iann_dior_type_beat_isolated_prod_perish.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $carlosId,
                'titulo_beat' => 'Iann Dior x Juice WRLD Pop Guitar Type Beat - Have Fun',
                'genero_musical' => 'Pop',
                'tempo_bpm' => 96,
                'tono_musical' => 'G',
                'estado_de_animo' => 'Ligero',
                'precio_base_licencia' => 16.99,
                'url_audio_previsualizacion' => 'media/audio/beats/iann_dior_x_juice_wrld_pop_guitar_type_beat_have_fun_prod_malloy_x_aidan_h.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $miguelId,
                'titulo_beat' => 'Kidd Keo Type Beat - Codeine',
                'genero_musical' => 'Drill',
                'tempo_bpm' => 142,
                'tono_musical' => 'A',
                'estado_de_animo' => 'Frio',
                'precio_base_licencia' => 20.99,
                'url_audio_previsualizacion' => 'media/audio/beats/kidd_keo_type_beat_codeine_prod_thatsauce.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $carlosId,
                'titulo_beat' => 'Kwengface x DigDat x C1 UK Drill Type Beat - Wrapped',
                'genero_musical' => 'Drill',
                'tempo_bpm' => 140,
                'tono_musical' => 'F#',
                'estado_de_animo' => 'Tenso',
                'precio_base_licencia' => 21.99,
                'url_audio_previsualizacion' => 'media/audio/beats/kwengface_x_digdat_x_c1_uk_drill_type_beat_wrapped_prod_by_3lackondabeat.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $miguelId,
                'titulo_beat' => 'Lil Baby x Meek Mill x Quay Global Type Beat - Aretha',
                'genero_musical' => 'Drill',
                'tempo_bpm' => 144,
                'tono_musical' => 'A#',
                'estado_de_animo' => 'Serio',
                'precio_base_licencia' => 20.99,
                'url_audio_previsualizacion' => 'media/audio/beats/lil_baby_x_meek_mill_x_quay_global_type_beat_2020_aretha_prod_glazer_noah.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $carlosId,
                'titulo_beat' => 'Lil Baby x Melodic Trap Type Beat - Smokin',
                'genero_musical' => 'Trap',
                'tempo_bpm' => 138,
                'tono_musical' => 'C',
                'estado_de_animo' => 'Melodico',
                'precio_base_licencia' => 19.99,
                'url_audio_previsualizacion' => 'media/audio/beats/lil_baby_x_melodic_trap_type_beat_smokin_prod_ilgu.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $miguelId,
                'titulo_beat' => 'Lil Mosey x Lil Skies x Lil Tecca Type Beat - Cold Like',
                'genero_musical' => 'Trap',
                'tempo_bpm' => 144,
                'tono_musical' => 'G#',
                'estado_de_animo' => 'Aereo',
                'precio_base_licencia' => 18.99,
                'url_audio_previsualizacion' => 'media/audio/beats/lil_mosey_x_lil_skies_x_lil_tecca_type_beat_cold_like_prod_snooza.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $carlosId,
                'titulo_beat' => 'Lil Tjay x Melodic Trap Type Beat - I Told You',
                'genero_musical' => 'Trap',
                'tempo_bpm' => 140,
                'tono_musical' => 'C#',
                'estado_de_animo' => 'Melodico',
                'precio_base_licencia' => 19.99,
                'url_audio_previsualizacion' => 'media/audio/beats/lil_tjay_x_melodic_trap_type_beat_i_told_you_prod_ilgu.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $miguelId,
                'titulo_beat' => 'Lil Tjay x PnB Rock Type Beat - Breath Away',
                'genero_musical' => 'Trap',
                'tempo_bpm' => 142,
                'tono_musical' => 'D#',
                'estado_de_animo' => 'Melodico',
                'precio_base_licencia' => 19.99,
                'url_audio_previsualizacion' => 'media/audio/beats/lil_tjay_x_pnb_rock_type_beat_breath_away_melodic_trap_type_beat_instrumental.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $carlosId,
                'titulo_beat' => 'Lil Tjay x PnB Rock Type Beat - I ll Be There',
                'genero_musical' => 'Trap',
                'tempo_bpm' => 144,
                'tono_musical' => 'E',
                'estado_de_animo' => 'Emotivo',
                'precio_base_licencia' => 20.99,
                'url_audio_previsualizacion' => 'media/audio/beats/lil_tjay_x_pnb_rock_type_beat_i_ll_be_there_ft_polo_g.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $miguelId,
                'titulo_beat' => 'MC Igu x Derek Type Beat - Pipe',
                'genero_musical' => 'Drill',
                'tempo_bpm' => 145,
                'tono_musical' => 'B',
                'estado_de_animo' => 'Agresivo',
                'precio_base_licencia' => 20.99,
                'url_audio_previsualizacion' => 'media/audio/beats/mc_igu_x_derek_type_beat_pipe_prod_johnny_lowd.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $carlosId,
                'titulo_beat' => 'Nav x The Weeknd Type Beat - I Don t Sleep At Night',
                'genero_musical' => 'Trap',
                'tempo_bpm' => 143,
                'tono_musical' => 'F',
                'estado_de_animo' => 'Nocturno',
                'precio_base_licencia' => 20.99,
                'url_audio_previsualizacion' => 'media/audio/beats/nav_x_the_weeknd_type_beat_i_don_t_sleep_at_night.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $miguelId,
                'titulo_beat' => 'OFB SJ x BandoKay x Double L z Type Beat - Half It',
                'genero_musical' => 'Drill',
                'tempo_bpm' => 140,
                'tono_musical' => 'G',
                'estado_de_animo' => 'Tenso',
                'precio_base_licencia' => 21.99,
                'url_audio_previsualizacion' => 'media/audio/beats/ofb_sj_x_bandokay_x_double_l_z_type_beat_half_it_prod_yoni.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $carlosId,
                'titulo_beat' => 'PnB Rock x Lil Tjay Type Beat - Pastime',
                'genero_musical' => 'Trap',
                'tempo_bpm' => 141,
                'tono_musical' => 'A',
                'estado_de_animo' => 'Melodico',
                'precio_base_licencia' => 19.99,
                'url_audio_previsualizacion' => 'media/audio/beats/pnb_rock_x_lil_tjay_type_beat_pastime_melodic_trap_type_beat_instrumental.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $miguelId,
                'titulo_beat' => 'PnB Rock x Lil Tjay Type Beat - Voices',
                'genero_musical' => 'Trap',
                'tempo_bpm' => 141,
                'tono_musical' => 'A#',
                'estado_de_animo' => 'Melodico',
                'precio_base_licencia' => 19.99,
                'url_audio_previsualizacion' => 'media/audio/beats/pnb_rock_x_lil_tjay_type_beat_voices_melodic_trap_type_beat_instrumental.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $carlosId,
                'titulo_beat' => 'Polo G x Lil Baby Type Beat - Patek',
                'genero_musical' => 'Trap',
                'tempo_bpm' => 145,
                'tono_musical' => 'D',
                'estado_de_animo' => 'Elegante',
                'precio_base_licencia' => 20.99,
                'url_audio_previsualizacion' => 'media/audio/beats/polo_g_x_lil_baby_type_beat_patek_melodic_trap_beat_instrumental.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $miguelId,
                'titulo_beat' => 'Polo G x Lil Tjay Type Beat - Millions',
                'genero_musical' => 'Trap',
                'tempo_bpm' => 144,
                'tono_musical' => 'E',
                'estado_de_animo' => 'Inspirador',
                'precio_base_licencia' => 20.99,
                'url_audio_previsualizacion' => 'media/audio/beats/polo_g_x_lil_tjay_type_beat_millions_prod_ramsey_beatz.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $carlosId,
                'titulo_beat' => 'Roddy Ricch x Mustard Type Beat - Fly Away',
                'genero_musical' => 'Trap',
                'tempo_bpm' => 143,
                'tono_musical' => 'F#',
                'estado_de_animo' => 'Brillante',
                'precio_base_licencia' => 19.99,
                'url_audio_previsualizacion' => 'media/audio/beats/roddy_ricch_x_mustard_type_beat_fly_away.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $miguelId,
                'titulo_beat' => 'RV x Ghosty UK Drill Type Beat - Underground',
                'genero_musical' => 'Drill',
                'tempo_bpm' => 140,
                'tono_musical' => 'G#',
                'estado_de_animo' => 'Oscuro',
                'precio_base_licencia' => 21.99,
                'url_audio_previsualizacion' => 'media/audio/beats/rv_x_ghosty_uk_drill_type_beat_underground_prod_migz.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $carlosId,
                'titulo_beat' => 'Sad Piano Juice WRLD Type Beat - Affection',
                'genero_musical' => 'Piano',
                'tempo_bpm' => 72,
                'tono_musical' => 'C',
                'estado_de_animo' => 'Triste',
                'precio_base_licencia' => 17.99,
                'url_audio_previsualizacion' => 'media/audio/beats/sad_piano_juice_wrld_type_beat_affection.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $miguelId,
                'titulo_beat' => 'Sad XXXTentacion x Killstation Type Beat - Plague',
                'genero_musical' => 'Emo Rap',
                'tempo_bpm' => 74,
                'tono_musical' => 'D#',
                'estado_de_animo' => 'Sombrio',
                'precio_base_licencia' => 17.99,
                'url_audio_previsualizacion' => 'media/audio/beats/sad_xxxtentacion_x_killstation_type_beat_plague.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $carlosId,
                'titulo_beat' => 'Sad XXXTentacion x NF Piano Type Beat - Relapse',
                'genero_musical' => 'Piano',
                'tempo_bpm' => 73,
                'tono_musical' => 'F',
                'estado_de_animo' => 'Reflexivo',
                'precio_base_licencia' => 17.99,
                'url_audio_previsualizacion' => 'media/audio/beats/sad_xxxtentacion_x_nf_piano_type_beat_relapse.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $miguelId,
                'titulo_beat' => 'Speed Melodic Type Beat - Trap Instrumental 2020',
                'genero_musical' => 'Trap',
                'tempo_bpm' => 138,
                'tono_musical' => 'A',
                'estado_de_animo' => 'Dinamico',
                'precio_base_licencia' => 18.99,
                'url_audio_previsualizacion' => 'media/audio/beats/speed_melodic_type_beat_trap_instrumental_2020.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $carlosId,
                'titulo_beat' => 'Travis Scott Type Beat 2019 - Callejero',
                'genero_musical' => 'Trap',
                'tempo_bpm' => 145,
                'tono_musical' => 'B',
                'estado_de_animo' => 'Potente',
                'precio_base_licencia' => 20.99,
                'url_audio_previsualizacion' => 'media/audio/beats/travis_scott_type_beat_2019_callejero_base_de_trap_instrumental_de_trap.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $miguelId,
                'titulo_beat' => 'Travis Scott x FRVRFRIDAY Type Beat - Fantasia',
                'genero_musical' => 'Trap',
                'tempo_bpm' => 126,
                'tono_musical' => 'G',
                'estado_de_animo' => 'Espacial',
                'precio_base_licencia' => 18.99,
                'url_audio_previsualizacion' => 'media/audio/beats/travis_scottfrvrfriday_type_beat_fantasia.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $carlosId,
                'titulo_beat' => 'Young Thug x Melodic Trap Type Beat - Gotti',
                'genero_musical' => 'Trap',
                'tempo_bpm' => 139,
                'tono_musical' => 'C#',
                'estado_de_animo' => 'Melodico',
                'precio_base_licencia' => 19.99,
                'url_audio_previsualizacion' => 'media/audio/beats/young_thug_x_melodic_trap_type_beat_gotti_prod_ilgu.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
            [
                'id_usuario' => $miguelId,
                'titulo_beat' => 'Young Thug x Tory Lanez Type Beat - Otherside',
                'genero_musical' => 'Trap',
                'tempo_bpm' => 144,
                'tono_musical' => 'D',
                'estado_de_animo' => 'Oscuro',
                'precio_base_licencia' => 20.99,
                'url_audio_previsualizacion' => 'media/audio/beats/young_thug_x_tory_lanez_type_beat_otherside_trap_instrumental_2019.mp3',
                'url_archivo_final' => null,
                'url_portada_beat' => 'media/img/nocheDeAmor.jpg',
                'activo_publicado' => 1,
                'fecha_publicacion' => now(),
            ],
        ];

        DB::table('beat')->insert($beats);
    }
}
